CREATE TABLE IF NOT EXISTS `settings` (
  `SETTING_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `PUBLIC` VARCHAR(30) NOT NULL UNIQUE,
  `EDITMODE` BOOLEAN NOT NULL 
);

INSERT INTO settings(PUBLIC, EDITMODE) VALUES
('showall', false)
