CREATE TABLE IF NOT EXISTS `reviews` (
  `REVIEW_ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(100) NOT NULL,
  `MESSAGE` VARCHAR(700) NOT NULL,
  `USER_ID` INT NOT NULL,
  `DATE` DATETIME DEFAULT NOW(),
  `isPublic` BOOLEAN DEFAULT FALSE,
  `editMode` BOOLEAN DEFAULT FALSE,
  `ANSWER` VARCHAR(200) DEFAULT NULL,
  
  PRIMARY KEY (`REVIEW_ID`),
  CONSTRAINT `USER_ID`    
  FOREIGN KEY (`USER_ID`)
    REFERENCES `users` (`USER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );
    
INSERT INTO reviews(TITLE, MESSAGE, USER_ID) VALUES
('Тестовый отзыв', 'Здесь могла быть Ваша реклама', 2);